# 4 Best Hybrid Search Configuration

This notebook runs different hybrid search configurations, calculates the metrics for each configuration and compares the results to the metrics calcuated after the baseline run from the previous notebook. 

We are using the same query set to have a fair comparison.

## Get queries

In [1]:
import pandas as pd
import numpy as np
import requests
import json
import mercury as mr
import itertools
from tqdm.notebook import tqdm_notebook

app = mr.App(title="Let's Run a Hybrid Search", static_notebook=True)

mercury.App

## Load Query Sets and Ratings

Use the query sets and created ratings/judgements from notebook 3.

In [2]:
# Set the boolean value accordingly to use either the small (small_b = True) or the large dataset (small_b = False).
small_b = False

if small_b:
    df_train = pd.read_csv('../data/query_train_small.csv')
    df_test = pd.read_csv('../data/query_test_small.csv')
if not small_b:
    df_train = pd.read_csv('../data/query_train.csv')
    df_test = pd.read_csv('../data/query_test.csv')
df_query_set = pd.concat([df_train, df_test])

In [3]:
# Import the ratings generated in the previous notebook
df_ratings = pd.read_csv('../data/ratings.csv', sep="\t", names=['query', 'docid', 'rating', 'idx'])#, index=False)
df_ratings

                        query       docid  rating   idx
0      #8 tags without string  B0751KS4ZW       0     0
1      #8 tags without string  B07541MJRV       2     0
2      #8 tags without string  B075WX3LFF       2     0
3      #8 tags without string  B076BBJYRN       2     0
4      #8 tags without string  B0772W8DPP       0     0
...                       ...         ...     ...   ...
93904                     眼镜框  B06XCPKJTV       3  4999
93905                     眼镜框  B01LZROY37       2  4999
93906                     眼镜框  B01A2O6AGQ       0  4999
93907                     眼镜框  B01030BYCE       3  4999
93908                     眼镜框  B07N2LY4PH       3  4999

[93909 rows x 4 columns]

In [4]:
df_queries = df_ratings.groupby(by='query', as_index=False).agg({
    'rating': ['count']
})
df_query_idx = df_queries['query']

In [5]:
df_query_idx = pd.DataFrame(df_query_idx)

df_query_idx = df_query_idx.reset_index()

df_query_idx = df_query_idx.rename(columns={'index': 'idx'})
df_query_idx

       idx                                  query
0        0                 #8 tags without string
1        1             $1 dollar toys not fidgets
2        2       $30 roblox gift card not digital
3        3  $60 ps4 that’s not gonna be on amazon
4        4  'm team jesus i'm not religious shirt
...    ...                                    ...
4995  4995            zoom eyepiece for telescope
4996  4996                            zumba shoes
4997  4997          zwave front door lock kwikset
4998  4998                                 zyrtec
4999  4999                                    眼镜框

[5000 rows x 2 columns]

## Query OpenSearch with the Hybrid Search Configurations

Let's make sure that we can execute hybrid search queries by creating a pipeline and using it in a query

In [6]:
keyword_weight = 0.3

In [7]:
neural_weight = round(1.0 - keyword_weight, 2)
print(f"Keyword Weight is {keyword_weight} and Neural Weight is {neural_weight}")

Keyword Weight is 0.3 and Neural Weight is 0.7

In [8]:
# Get model_id
# We are assuming that the installation has only one model. Change this if you have more models 
# and need to pick a specific one

url = "http://localhost:9200/_plugins/_ml/models/_search"

headers = {
    'Content-Type': 'application/json'
}

payload = {
  "query": {
    "match_all": {}
  },
  "size": 1
}

response = requests.request("POST", url, headers=headers, data=json.dumps(payload))

model_id = response.json()['hits']['hits'][0]['_source']['model_id']

In [9]:
normalization = 'l2'
combination = 'arithmetic_mean'
keyword = 0.3
vector = 0.7
pipeline = 'hybrid-search-pipeline'

url = "http://localhost:9200/_search/pipeline/" + pipeline

print(f"Setting default model id to: {model_id}")
payload = {
  "request_processors": [
    {
      "neural_query_enricher" : {
        "description": "Sets the default model ID at index and field levels",
        "default_model_id": model_id,
        "neural_field_default_id": {
           "title_embeddings": model_id
        }
      }
    }
  ],
  "phase_results_processors": [
    {
      "normalization-processor": {
        "normalization": {
          "technique": "min_max"
        },
        "combination": {
          "technique": "arithmetic_mean",
          "parameters": {
            "weights": [
              keyword_weight,
              neural_weight
            ]
          }
        }
      }
    }
  ]    
}


response = requests.request("PUT", url, headers=headers, data=json.dumps(payload))
mr.JSON(response.json(), level=4)

Setting default model id to: OF4X4ZgBj0VqznIp6xgG

In [10]:
url = "http://localhost:9200/ecommerce/_search?search_pipeline=" + pipeline
    
# iterate over all query strings and send a hybrid search query to OpenSearch with the set pipeline
query = "iphone case"

payload = {
  "_source": {
    "excludes": [
      "title_embedding"
    ]
  },
  "query": {
    "hybrid": {
      "queries": [
        {
          "multi_match" : {
              "type":       "best_fields",
              "fields":     [
                "product_id^100",
                "product_bullet_point^3",
                "product_color^2",
                "product_brand^5",
                "product_description",
                "product_title^10"
              ],
              "operator":   "and",
              "query":      query
            }
        },
        {
          "neural": {
            "title_embedding": {
              "query_text": query,
              "k": 100
            }
          }
        }
      ]
    }
  },
  "size": 100
}

response = requests.request("POST", url, headers=headers, data=json.dumps(payload)).json()

In [11]:
mr.JSON(response, level=2)

## Try out all Hybrid Search Configurations

Our global hybrid search optimization notebook tries out 66 parameter combinations for hybrid search with the following set:
* normalization technique: [`l2`, `min_max`]
* combination technique: [`arithmetic_mean`, `harmonic_mean`, `geometric_mean`]
* keyword search weight: [`0.0`, `0.1`, `0.2`, `0.3`, `0.4`, `0.5`, `0.6`, `0.7`, `0.8`, `0.9`, `1.0`]
* neural search weight: [`1.0`, `0.9`, `0.8`, `0.7`, `0.6`, `0.5`, `0.4`, `0.3`, `0.2`, `0.1`, `0.0`]

Neural and keyword search weights always add up to `1.0`, so a keyword search weight of `0.1` automatically comes with a neural search weight of `0.9`, a keyword search weight of `0.2` comes with a neural search weight of `0.8`, etc.

### Create a DataFrame with all possible combinations of hybrid search configurations

In [12]:
# Define the possible values for each column
normalization_values = ['min_max', 'l2']
combination_values = ['arithmetic_mean', 'harmonic_mean', 'geometric_mean']
keyword_values = [round(i * 0.1, 1) for i in range(11)]

# Create all possible combinations of normalization, combination, and keyword
combinations = list(itertools.product(normalization_values, combination_values, keyword_values))

# Calculate the vector as 1.0 - keyword
data = [(norm, comb, kw, 1.0 - kw) for norm, comb, kw in combinations]

# Create DataFrame
df_hybrid_search_params = pd.DataFrame(data, columns=['normalization', 'combination', 'keyword', 'vector'])

# Create a column with a pipeline name made up of its components
df_hybrid_search_params['pipeline'] = df_hybrid_search_params.normalization.apply(str) + \
    df_hybrid_search_params.combination.apply(str) + df_hybrid_search_params.keyword.apply(str)

df_hybrid_search_params.head()

  normalization      combination  keyword  vector                   pipeline
0       min_max  arithmetic_mean      0.0     1.0  min_maxarithmetic_mean0.0
1       min_max  arithmetic_mean      0.1     0.9  min_maxarithmetic_mean0.1
2       min_max  arithmetic_mean      0.2     0.8  min_maxarithmetic_mean0.2
3       min_max  arithmetic_mean      0.3     0.7  min_maxarithmetic_mean0.3
4       min_max  arithmetic_mean      0.4     0.6  min_maxarithmetic_mean0.4

### Iterate over all hybrid search configurations

We execute each query from the training data set against each of the hybrid search configuration and store the 100 first results in a DataFrame for the upcoming metrics calculation

In [13]:
from concurrent.futures import ThreadPoolExecutor

In [14]:
# filtered_queries = df_query_idx[df_query_idx['query'].isin(df_train['query_string'])].head(100)
filtered_queries = df_query_idx[df_query_idx['query'].isin(df_train['query_string'])]

def process_config(config):
    results = []
    norm = config[1]
    combi = config[2]
    keywordness = round(config[3],2)
    neuralness = round(config[4], 2)
    pipeline_name = config[5]

    # Set pipeline 
     
    url = "http://localhost:9200/ecommerce/_search"
    
    # iterate over all query strings and send a hybrid search query to OpenSearch with the set pipeline
    for query in filtered_queries.itertuples():
    
        payload = {
          "_source": {
            "excludes": [
              "title_embedding"
            ]
          },
          "query": {
            "hybrid": {
              "queries": [
                {
                  "multi_match" : {
                      "type":       "best_fields",
                      "fields":     [
                        "product_id^100",
                        "product_bullet_point^3",
                        "product_color^2",
                        "product_brand^5",
                        "product_description",
                        "product_title^10"
                      ],
                      "operator":   "and",
                      "query":      query[2]
                    }
                },
                {
                  "neural": {
                    "title_embedding": {
                      "query_text": query[2],
                      "k": 100
                    }
                  }
                }
              ]
            }
          },
          "search_pipeline": {
            "request_processors": [
              {
                "neural_query_enricher" : {
                  "description": "one of many search pipelines for experimentation",
                  "default_model_id": model_id,
                  "neural_field_default_id": {
                    "title_embeddings": model_id
                  }
                }
              }
            ],
            "phase_results_processors": [
              {
                "normalization-processor": {
                  "normalization": {
                    "technique": norm
                  },
                  "combination": {
                    "technique": combi,
                    "parameters": {
                      "weights": [
                        keywordness,
                        neuralness
                      ]
                    }
                  }
                }
              }
            ]    
          },
          "size": 100
        }
    
        response = requests.request("POST", url, headers=headers, data=json.dumps(payload)).json()
        #print(response)
        # store results per pipeline_id
        position = 0
        for hit in response['hits']['hits']:
            # create a new row for the DataFrame and append it
            row = { 'query_id' : str(query[1]), 'query_string': query[2], 'product_id' : hit["_id"], 'position' : str(position), 'relevance' : hit["_score"], 'run': pipeline_name }
            # work with two for loops:
            # 1) one to iterate over the list of queries and have a query id instead of a query
            # 2) another one to iterate over the result sets to have the position of the result in the result set 
            
            # DataFrame with columns:
            # query_id: the id of the query as the trec_eval tool needs a numeric id rather than a query string as an identifier
            # product_id: the id of the product in the hit list
            # position: the position of the product in the result set
            # relevance: relevance as given by the search engine
            # run: the name of the query pipeline
            results.append(row)
    
            position += 1
    return results  # Returns a list of rows for each config

In [15]:
output_file = '../data/results_large_qs-2025-08-28.csv'

with ThreadPoolExecutor(max_workers=4) as executor:
    for config_results in tqdm_notebook(executor.map(process_config, df_hybrid_search_params.itertuples())):
        print(config_results)
        # Append each config's results to CSV file
        pd.DataFrame(config_results).to_csv(output_file, mode='a', header=False, index=False)

0it [00:00, ?it/s]

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [16]:
df_relevance = pd.read_csv(output_file, names=["query_id", "query_string", "product_id", "position", "relevance", "run"])

In [17]:
df_relevance.head(3)

,query_id,query_string,product_id,position,relevance,run
0,0,#8 tags without string,B07SPL5VG3,0,1.000000,min_maxarithmetic_mean0.0
1,0,#8 tags without string,B07BZ7PHYL,1,0.920451,min_maxarithmetic_mean0.0
2,0,#8 tags without string,B07CV44YR8,2,0.919778,min_maxarithmetic_mean0.0

There are up to 100 results per query, so there are up to _number of queries_ * 100 rows per pipeline in the resulting DataFrame

In [18]:
df_relevance[df_relevance['run'] == "min_maxarithmetic_mean0.0"].shape[0]

334668

In [19]:
df_relevance.shape[0]

22097924

# Calculate Metrics per Pipeline

In [20]:
df_ratings.columns = ['query_string', 'product_id', 'rating', 'query_id']
df_ratings.head(3)

             query_string  product_id  rating  query_id
0  #8 tags without string  B0751KS4ZW       0         0
1  #8 tags without string  B07541MJRV       2         0
2  #8 tags without string  B075WX3LFF       2         0

In [21]:
# Make sure ids are strings - otherwise the merge operation might cause an error
df_relevance['query_id'] = df_relevance['query_id'].astype(str)
df_relevance['position'] = df_relevance['position'].astype(int)
df_ratings['query_id'] = df_ratings['query_id'].astype(str)
# Remove duplicates from the ratings DataFrame
df_unique_ratings = df_ratings.drop_duplicates(subset=['product_id', 'query_id'])

In [22]:
# Merge results on query_id and product_id so that the resulting DataFrame has the ratings together with the search results
# Validations helps us make sure that we have only one rating for each query-doc pair. We have identical query-doc pairs per
# search pipeline but we can only have one rating for these.
df_merged = df_relevance.merge(df_unique_ratings, on=['query_id', 'product_id'], how='left', validate='many_to_one')
df_merged = df_merged.drop(columns=['query_string_y'])

df_merged.head(3)
df_merged = df_merged.rename(columns={"query_string_x": "query_string"})

In [23]:
# Count the rows without ratings - the higher the count is the less reliable the results will be
nan_count_rating = df_merged['rating'].isna().sum()
print(f"There are {df_merged.shape[0]} rows and {nan_count_rating} do not contain a rating")

There are 22097924 rows and 20080427 do not contain a rating

## Calculate Metrics

Iterate over the queries in the query set, calculate the three metrics dcg@10, ndcg@10 and precision@10 and store the results for every query in a DataFrame

In [24]:
df_ratings.head(3)

             query_string  product_id  rating query_id
0  #8 tags without string  B0751KS4ZW       0        0
1  #8 tags without string  B07541MJRV       2        0
2  #8 tags without string  B075WX3LFF       2        0

In [25]:
# import from shared utils file metrics.py
from utils import metrics

metrics = [
    ("dcg", metrics.dcg_at_10, None),
    ("ndcg", metrics.ndcg_at_10, None),
    ("prec@10", metrics.precision_at_k, None),
    ("ratio_of_ratings", metrics.ratio_of_ratings, None)
]

In [26]:
reference = {query: df for query, df in df_ratings.groupby("query_string")}

df_metrics = []
for m_name, m_function, ref_search in metrics:
    for (query_string, run), df_gr in df_merged.groupby(["query_string", "run"]):
        metric = m_function(df_gr, reference=reference[query_string])
        df_metrics.append(pd.DataFrame({
            "query": [query_string],
            "pipeline": [run],
            "metric": [m_name],
            "value": [metric],
        }))
df_metrics = pd.concat(df_metrics)

In [27]:
df_metrics

,query,pipeline,metric,value
0,#8 tags without string,l2arithmetic_mean0.0,dcg,8.784672
0,#8 tags without string,l2arithmetic_mean0.1,dcg,25.513576
0,#8 tags without string,l2arithmetic_mean0.2,dcg,25.513576
0,#8 tags without string,l2arithmetic_mean0.3,dcg,26.459970
0,#8 tags without string,l2arithmetic_mean0.4,dcg,26.818740
...,...,...,...,...
0,眼镜框,min_maxharmonic_mean0.6,ratio_of_ratings,0.000000
0,眼镜框,min_maxharmonic_mean0.7,ratio_of_ratings,0.000000
0,眼镜框,min_maxharmonic_mean0.8,ratio_of_ratings,0.000000
0,眼镜框,min_maxharmonic_mean0.9,ratio_of_ratings,0.000000
0,眼镜框,min_maxharmonic_mean1.0,ratio_of_ratings,0.000000

In [28]:
df_metrics.to_csv('../data/metrics_query_train_large_qs-2025-08-28.csv', index=False)

## Calculate Metrics per Pipeline by Averaging the Query Metrics

In [29]:
df_metrics_per_pipeline = df_metrics.pivot_table(index="pipeline", columns="metric", values="value", aggfunc=lambda x: x.mean().round(2))
df_metrics_per_pipeline = df_metrics_per_pipeline.reset_index()

### Top five Pipelines by NDCG@10 Descending

In [30]:
df_metrics_per_pipeline.sort_values(by='ndcg', ascending=False).head(5)

metric                   pipeline    dcg  ndcg  prec@10  ratio_of_ratings
9            l2arithmetic_mean0.9  10.03  0.27     0.30              0.31
38      min_maxarithmetic_mean0.5   9.88  0.27     0.29              0.30
39      min_maxarithmetic_mean0.6  10.06  0.27     0.30              0.31
4            l2arithmetic_mean0.4  10.10  0.27     0.30              0.31
5            l2arithmetic_mean0.5  10.21  0.27     0.30              0.32

### Top five Pipelines by DCG@10 Descending

In [31]:
df_metrics_per_pipeline.sort_values(by='dcg', ascending=False).head(5)

metric              pipeline    dcg  ndcg  prec@10  ratio_of_ratings
5       l2arithmetic_mean0.5  10.21  0.27      0.3              0.32
6       l2arithmetic_mean0.6  10.18  0.27      0.3              0.31
7       l2arithmetic_mean0.7  10.13  0.27      0.3              0.31
4       l2arithmetic_mean0.4  10.10  0.27      0.3              0.31
8       l2arithmetic_mean0.8  10.09  0.27      0.3              0.31

### Top five Pipelines by Precision@10 Descending

In [37]:
df_metrics_per_pipeline.sort_values(by='prec@10', ascending=False).head(5)

metric                   pipeline    dcg  ndcg  prec@10  ratio_of_ratings
8            l2arithmetic_mean0.8  10.09  0.27      0.3              0.31
39      min_maxarithmetic_mean0.6  10.06  0.27      0.3              0.31
4            l2arithmetic_mean0.4  10.10  0.27      0.3              0.31
5            l2arithmetic_mean0.5  10.21  0.27      0.3              0.32
6            l2arithmetic_mean0.6  10.18  0.27      0.3              0.31

In [33]:
df_merged.to_csv('../data/results_and_ratings_query_set_large_qs-2025-08-28.csv')

In [38]:
# Use a query from the query set to see the results by pipeline

query = '#8 tags without string'

df_merged[(df_merged['query_string'] == query) & (df_merged['run'] == 'min_maxarithmetic_mean0.0')]

,query_id,query_string,product_id,position,relevance,run,rating
0,0,#8 tags without string,B07SPL5VG3,0,1.000000,min_maxarithmetic_mean0.0,NaN
1,0,#8 tags without string,B07BZ7PHYL,1,0.920451,min_maxarithmetic_mean0.0,NaN
2,0,#8 tags without string,B07CV44YR8,2,0.919778,min_maxarithmetic_mean0.0,NaN
3,0,#8 tags without string,B082VY8HHP,3,0.854454,min_maxarithmetic_mean0.0,NaN
4,0,#8 tags without string,B076BBJYRN,4,0.774074,min_maxarithmetic_mean0.0,2.0
...,...,...,...,...,...,...,...
94,0,#8 tags without string,B083P2WFZ9,94,0.001000,min_maxarithmetic_mean0.0,NaN
95,0,#8 tags without string,B085DFGMCM,95,0.000000,min_maxarithmetic_mean0.0,NaN
96,0,#8 tags without string,B00OLNG12I,96,0.000000,min_maxarithmetic_mean0.0,0.0
97,0,#8 tags without string,B078T91YY7,97,0.000000,min_maxarithmetic_mean0.0,NaN
98,0,#8 tags without string,B013ORXI4A,98,0.000000,min_maxarithmetic_mean0.0,3.0

In [39]:
df_metrics[(df_metrics['query'] == query) & (df_metrics['pipeline'] == 'min_maxarithmetic_mean0.0')]

,query,pipeline,metric,value
0,#8 tags without string,min_maxarithmetic_mean0.0,dcg,8.784672
0,#8 tags without string,min_maxarithmetic_mean0.0,ndcg,0.175339
0,#8 tags without string,min_maxarithmetic_mean0.0,prec@10,0.500000
0,#8 tags without string,min_maxarithmetic_mean0.0,ratio_of_ratings,0.500000

## Evaluate the Best Hybrid Search Configuration

We identified the best hybrid search configuration by running our training set against the different combinations.

Now we take the winning configuration and execute the test set against this configuration. We can use the calculated numbers then to compare it with our baseline from notebook 3.

In [40]:
# Set parameters for best hybrid search config:

norm = "l2"
combi = "arithmetic_mean"
keywordness = 0.5
neuralness = 0.5
pipeline_name = "l2arithmetic_mean0.5"

In [41]:
df_relevance_test = pd.DataFrame()
url = "http://localhost:9200/ecommerce/_search"

# iterate over all query strings in the test set and send a hybrid search query to OpenSearch with the set configuration
for query in tqdm_notebook(df_query_idx[df_query_idx['query'].isin(df_test['query_string'])].itertuples()):

    payload = {
      "_source": {
        "excludes": [
          "title_embedding"
        ]
      },
      "query": {
        "hybrid": {
          "queries": [
            {
              "multi_match" : {
                  "type":       "best_fields",
                  "fields":     [
                    "product_id^100",
                    "product_bullet_point^3",
                    "product_color^2",
                    "product_brand^5",
                    "product_description",
                    "product_title^10"
                  ],
                  "operator":   "and",
                  "query":      query[2]
                }
            },
            {
              "neural": {
                "title_embedding": {
                  "query_text": query[2],
                  "k": 100
                }
              }
            }
          ]
        }
      },
      "search_pipeline": {
        "request_processors": [
          {
            "neural_query_enricher" : {
              "description": "one of many search pipelines for experimentation",
              "default_model_id": model_id,
              "neural_field_default_id": {
                "title_embeddings": model_id
              }
            }
          }
        ],
        "phase_results_processors": [
          {
            "normalization-processor": {
              "normalization": {
                "technique": norm
              },
              "combination": {
                "technique": combi,
                "parameters": {
                  "weights": [
                    keywordness,
                    neuralness
                  ]
                }
              }
            }
          }
        ]    
      },
      "size": 100
    }

    response = requests.request("POST", url, headers=headers, data=json.dumps(payload)).json()
    # store results per pipeline_id
    position = 0
    for hit in response['hits']['hits']:
        # create a new row for the DataFrame and append it
        row = { 'query_id' : str(query[1]), 'query_string': query[2], 'product_id' : hit["_id"], 'position' : str(position), 'relevance' : hit["_score"], 'run': pipeline_name }

        new_row_df = pd.DataFrame([row])
        df_relevance_test = pd.concat([df_relevance_test, new_row_df], ignore_index=True)
        #print("%(id)s %(title)s: %(name)s" % hit["_source"])
        position += 1
    
    # work with two for loops:
    # 1) one to iterate over the list of queries and have a query id instead of a query
    # 2) another one to iterate over the result sets to have the position of the result in the result set 
    
    # DataFrame with columns:
    # query_id: the id of the query as the trec_eval tool needs a numeric id rather than a query string as an identifier
    # product_id: the id of the product in the hit list
    # position: the position of the product in the result set
    # relevance: relevance as given by the search engine
    # run: the name of the query pipeline

0it [00:00, ?it/s]

In [42]:
df_relevance_test.head(3)

,query_id,query_string,product_id,position,relevance,run
0,8,- we are not such things,B00L4B5MWA,0,0.061835,l2arithmetic_mean0.5
1,8,- we are not such things,B077CLM3BL,1,0.059967,l2arithmetic_mean0.5
2,8,- we are not such things,B09B4R3ND2,2,0.057821,l2arithmetic_mean0.5

In [43]:
# Make sure ids are strings - otherwise the merge operation might cause an error
df_relevance_test['query_id'] = df_relevance_test['query_id'].astype(str)
df_relevance_test['position'] = df_relevance_test['position'].astype(int)

In [44]:
# Merge results on query_id and product_id so that the resulting DataFrame has the ratings together with the search results
# Validations helps us make sure that we have only one rating for each query-doc pair. We have identical query-doc pairs per
# search pipeline but we can only have one rating for these.
df_merged_test = df_relevance_test.merge(df_unique_ratings, on=['query_id', 'product_id'], how='left', validate='many_to_one')
df_merged_test = df_merged_test.drop(columns=['query_string_y'])

df_merged_test.head(3)
df_merged_test = df_merged_test.rename(columns={"query_string_x": "query_string"})

In [45]:
df_metrics_test_set = []
for m_name, m_function, ref_search in metrics:
    for (query_string, run), df_gr in df_merged_test.groupby(["query_string", "run"]):
        metric = m_function(df_gr, reference=reference[query_string])
        df_metrics_test_set.append(pd.DataFrame({
            "query": [query_string],
            "pipeline": [run],
            "metric": [m_name],
            "value": [metric],
        }))
df_metrics_test_set = pd.concat(df_metrics_test_set)

In [46]:
df_metrics_test_set.head(3)

,query,pipeline,metric,value
0,- we are not such things,l2arithmetic_mean0.5,dcg,1.292030
0,02cool spray water bottle for drinking not fla...,l2arithmetic_mean0.5,dcg,10.118654
0,0pi nail polish i'm not really a waitress,l2arithmetic_mean0.5,dcg,7.000000

In [47]:
df_metrics_test_set.to_csv('../data/metrics_query_test_large_qs-2025-08-28.csv', index=False)

In [48]:
df_metrics_test_per_pipeline = df_metrics_test_set.pivot_table(index="pipeline", columns="metric", values="value", aggfunc=lambda x: x.mean().round(2))
df_metrics_test_per_pipeline = df_metrics_test_per_pipeline.reset_index()

In [49]:
df_metrics_test_per_pipeline

metric              pipeline    dcg  ndcg  prec@10  ratio_of_ratings
0       l2arithmetic_mean0.5  10.21  0.27      0.3              0.32

## Metrics Compared to Baseline

Compared to the baseline of the previous notebook this is an improvement:

| Metric    | Baseline BM25 | Global Hybrid Search Optimizer 
| -------- | ------- | ------- |
| DCG  | 6.03    | 6.21    |
| NDCG | 0.26    | 0.28    |
| Precision    | 0.30     | 0.32    |

## Run Test Set for All Pipeline Configurations

In [50]:
filtered_queries = df_query_idx[df_query_idx['query'].isin(df_test['query_string'])]

In [51]:
filtered_queries.shape[0]

1000

In [55]:
output_file = '../data/results_all_pipelines_test_large_qs-2024-08-28.csv'

with ThreadPoolExecutor(max_workers=4) as executor:
    for config_results in tqdm_notebook(executor.map(process_config, df_hybrid_search_params.itertuples())):
        # Append each config's results to CSV file
        pd.DataFrame(config_results).to_csv(output_file, mode='a', header=False, index=False)

0it [00:00, ?it/s]

In [56]:
df_relevance = pd.read_csv(output_file, names=["query_id", "query_string", "product_id", "position", "relevance", "run"])

In [57]:
df_relevance.head(3)

,query_id,query_string,product_id,position,relevance,run
0,8,- we are not such things,B00L4B5MWA,0,1.000000,min_maxarithmetic_mean0.0
1,8,- we are not such things,B08WRDMYTH,1,0.598815,min_maxarithmetic_mean0.0
2,8,- we are not such things,B08TV3XGZ4,2,0.476326,min_maxarithmetic_mean0.0

In [58]:
df_relevance[df_relevance['run'] == "min_maxarithmetic_mean0.0"].shape[0]

84149

In [59]:
df_relevance.shape[0]

5562199

# Calculate Metrics per Pipeline

In [60]:
df_ratings.columns = ['query_string', 'product_id', 'rating', 'query_id']
df_ratings.head(3)

             query_string  product_id  rating query_id
0  #8 tags without string  B0751KS4ZW       0        0
1  #8 tags without string  B07541MJRV       2        0
2  #8 tags without string  B075WX3LFF       2        0

In [61]:
# Make sure ids are strings - otherwise the merge operation might cause an error
df_relevance['query_id'] = df_relevance['query_id'].astype(str)
df_relevance['position'] = df_relevance['position'].astype(int)

In [62]:
# Merge results on query_id and product_id so that the resulting DataFrame has the ratings together with the search results
# Validations helps us make sure that we have only one rating for each query-doc pair. We have identical query-doc pairs per
# search pipeline but we can only have one rating for these.
df_merged = df_relevance.merge(df_unique_ratings, on=['query_id', 'product_id'], how='left', validate='many_to_one')
df_merged = df_merged.drop(columns=['query_string_y'])

df_merged.head(3)
df_merged = df_merged.rename(columns={"query_string_x": "query_string"})

In [63]:
# Count the rows without ratings - the higher the count is the less reliable the results will be
nan_count_rating = df_merged['rating'].isna().sum()
print(f"There are {df_merged.shape[0]} rows and {nan_count_rating} do not contain a rating")

There are 5562199 rows and 5055017 do not contain a rating

## Calculate Metrics

Iterate over the queries in the query set, calculate the three metrics dcg@10, ndcg@10 and precision@10 and store the results for every query in a DataFrame

In [64]:
df_ratings.head(3)

             query_string  product_id  rating query_id
0  #8 tags without string  B0751KS4ZW       0        0
1  #8 tags without string  B07541MJRV       2        0
2  #8 tags without string  B075WX3LFF       2        0

In [65]:
df_merged_test[df_merged_test['run'] == 'l2arithmetic_mean0.4'].head(10)

Empty DataFrame
Columns: [query_id, query_string, product_id, position, relevance, run, rating]
Index: []

In [66]:
df_merged[df_merged['run'] == 'l2arithmetic_mean0.4'].head(10)

,query_id,query_string,product_id,position,relevance,run,rating
3117810,8,- we are not such things,B00L4B5MWA,0,0.074202,l2arithmetic_mean0.4,NaN
3117811,8,- we are not such things,B08WRDMYTH,1,0.069195,l2arithmetic_mean0.4,2.0
3117812,8,- we are not such things,B08TV3XGZ4,2,0.067666,l2arithmetic_mean0.4,NaN
3117813,8,- we are not such things,B07MRKPHKR,3,0.067666,l2arithmetic_mean0.4,NaN
3117814,8,- we are not such things,1937578313,4,0.066984,l2arithmetic_mean0.4,NaN
3117815,8,- we are not such things,B078JNBVFY,5,0.066984,l2arithmetic_mean0.4,NaN
3117816,8,- we are not such things,B08GMCCFSN,6,0.066334,l2arithmetic_mean0.4,NaN
3117817,8,- we are not such things,B08GMC2Q1S,7,0.066334,l2arithmetic_mean0.4,NaN
3117818,8,- we are not such things,035813143X,8,0.066095,l2arithmetic_mean0.4,NaN
3117819,8,- we are not such things,B00SQ0O296,9,0.065932,l2arithmetic_mean0.4,NaN

In [67]:
df_metrics = []
for m_name, m_function, ref_search in metrics:
    for (query_string, run), df_gr in df_merged.groupby(["query_string", "run"]):
        metric = m_function(df_gr, reference=reference[query_string])
        df_metrics.append(pd.DataFrame({
            "query": [query_string],
            "pipeline": [run],
            "metric": [m_name],
            "value": [metric],
        }))
df_metrics = pd.concat(df_metrics)

In [68]:
df_metrics[df_metrics['pipeline'] == 'l2arithmetic_mean0.4']

,query,pipeline,metric,value
0,- we are not such things,l2arithmetic_mean0.4,dcg,1.892789
0,02cool spray water bottle for drinking not fla...,l2arithmetic_mean0.4,dcg,10.118654
0,0pi nail polish i'm not really a waitress,l2arithmetic_mean0.4,dcg,7.000000
0,1 14 brown leather belt without buckle,l2arithmetic_mean0.4,dcg,3.000000
0,1 flexible 8x10 mirror not sheet,l2arithmetic_mean0.4,dcg,6.984845
...,...,...,...,...
0,z590 motherboards,l2arithmetic_mean0.4,ratio_of_ratings,0.800000
0,zinc liquid supplement,l2arithmetic_mean0.4,ratio_of_ratings,0.700000
0,zoom eyepiece for telescope,l2arithmetic_mean0.4,ratio_of_ratings,0.500000
0,zumba shoes,l2arithmetic_mean0.4,ratio_of_ratings,0.300000
0,zyrtec,l2arithmetic_mean0.4,ratio_of_ratings,0.400000

In [69]:
df_metrics.head(5)

                      query              pipeline metric     value
0  - we are not such things  l2arithmetic_mean0.0    dcg  1.892789
0  - we are not such things  l2arithmetic_mean0.1    dcg  1.892789
0  - we are not such things  l2arithmetic_mean0.2    dcg  1.892789
0  - we are not such things  l2arithmetic_mean0.3    dcg  1.892789
0  - we are not such things  l2arithmetic_mean0.4    dcg  1.892789

In [70]:
df_metrics.to_csv('../data/metrics_query_test_large_qs_all_pipelines-2025-08-28.csv', index=False)

## Calculate Metrics per Pipeline by Averaging the Query Metrics

In [71]:
df_metrics_per_pipeline = df_metrics.pivot_table(index="pipeline", columns="metric", values="value", aggfunc=lambda x: x.mean().round(2))
df_metrics_per_pipeline = df_metrics_per_pipeline.reset_index()

### Top five Pipelines by NDCG@10 Descending

In [72]:
df_metrics_per_pipeline.sort_values(by='ndcg', ascending=False).head(5)

metric                   pipeline    dcg  ndcg  prec@10  ratio_of_ratings
42      min_maxarithmetic_mean0.9   9.99  0.27     0.29              0.31
7            l2arithmetic_mean0.7  10.07  0.27     0.30              0.31
40      min_maxarithmetic_mean0.7  10.15  0.27     0.30              0.31
41      min_maxarithmetic_mean0.8  10.13  0.27     0.30              0.31
38      min_maxarithmetic_mean0.5   9.94  0.27     0.29              0.31

### Top five Pipelines by DCG@10 Descending

In [73]:
df_metrics_per_pipeline.sort_values(by='dcg', ascending=False).head(5)

metric                   pipeline    dcg  ndcg  prec@10  ratio_of_ratings
5            l2arithmetic_mean0.5  10.21  0.27      0.3              0.32
6            l2arithmetic_mean0.6  10.17  0.27      0.3              0.31
40      min_maxarithmetic_mean0.7  10.15  0.27      0.3              0.31
41      min_maxarithmetic_mean0.8  10.13  0.27      0.3              0.31
4            l2arithmetic_mean0.4  10.11  0.27      0.3              0.31

### Top five Pipelines by Precision@10 Descending

In [74]:
df_metrics_per_pipeline.sort_values(by='prec@10', ascending=False).head(5)

metric                   pipeline    dcg  ndcg  prec@10  ratio_of_ratings
9            l2arithmetic_mean0.9  10.04  0.27      0.3              0.31
40      min_maxarithmetic_mean0.7  10.15  0.27      0.3              0.31
39      min_maxarithmetic_mean0.6  10.10  0.27      0.3              0.31
4            l2arithmetic_mean0.4  10.11  0.27      0.3              0.31
5            l2arithmetic_mean0.5  10.21  0.27      0.3              0.32

In [75]:
df_merged.to_csv('../data/results_and_ratings_query_set_large_qs_test_all_pipelines-2025-08-28.csv')

In [81]:
# Use a query from the query set to see the results by pipeline

query = '- we are not such things'

df_merged[(df_merged['query_string'] == query) & (df_merged['run'] == 'min_maxarithmetic_mean0.0')]

,query_id,query_string,product_id,position,relevance,run,rating
0,8,- we are not such things,B00L4B5MWA,0,1.000000,min_maxarithmetic_mean0.0,NaN
1,8,- we are not such things,B08WRDMYTH,1,0.598815,min_maxarithmetic_mean0.0,2.0
2,8,- we are not such things,B08TV3XGZ4,2,0.476326,min_maxarithmetic_mean0.0,NaN
3,8,- we are not such things,B07MRKPHKR,3,0.476326,min_maxarithmetic_mean0.0,NaN
4,8,- we are not such things,1937578313,4,0.421658,min_maxarithmetic_mean0.0,NaN
...,...,...,...,...,...,...,...
95,8,- we are not such things,B07RW8TLZD,95,0.000000,min_maxarithmetic_mean0.0,NaN
96,8,- we are not such things,B07PY3529T,96,0.000000,min_maxarithmetic_mean0.0,NaN
97,8,- we are not such things,B07RDDB7ZY,97,0.000000,min_maxarithmetic_mean0.0,NaN
98,8,- we are not such things,B07FSFF9RW,98,0.000000,min_maxarithmetic_mean0.0,NaN
99,8,- we are not such things,B07D21LN3R,99,0.000000,min_maxarithmetic_mean0.0,NaN

In [77]:
df_metrics[(df_metrics['query'] == query) & (df_metrics['pipeline'] == 'min_maxarithmetic_mean0.0')]

Empty DataFrame
Columns: [query, pipeline, metric, value]
Index: []

In [78]:
df_merged_test

,query_id,query_string,product_id,position,relevance,run,rating
0,8,- we are not such things,B00L4B5MWA,0,0.061835,l2arithmetic_mean0.5,NaN
1,8,- we are not such things,B077CLM3BL,1,0.059967,l2arithmetic_mean0.5,NaN
2,8,- we are not such things,B09B4R3ND2,2,0.057821,l2arithmetic_mean0.5,NaN
3,8,- we are not such things,B08WRDMYTH,3,0.057663,l2arithmetic_mean0.5,2.0
4,8,- we are not such things,B08TV3XGZ4,4,0.056389,l2arithmetic_mean0.5,NaN
...,...,...,...,...,...,...,...
84681,4998,zyrtec,B074F2468B,91,0.022174,l2arithmetic_mean0.5,2.0
84682,4998,zyrtec,B00G9E1GYA,92,0.022174,l2arithmetic_mean0.5,2.0
84683,4998,zyrtec,B001BJDJEI,93,0.013296,l2arithmetic_mean0.5,NaN
84684,4998,zyrtec,B01MZCMPOL,94,0.009518,l2arithmetic_mean0.5,NaN
84685,4998,zyrtec,B01N36QHUE,95,0.009518,l2arithmetic_mean0.5,NaN

In [79]:
df_merged_test.to_csv('../data/results_and_ratings_query_set_large_qs_test_best_pipeline-2025-08-28.csv', index=False)

In [80]:
df_merged[df_merged['run'] == 'l2arithmetic_mean0.5'].to_csv('../data/results_and_ratings_query_set_large_qs_test_all_pipelines_l2a05-2025-08-28.csv', index=False)